alert_rules:
  AAPL:
    price_threshold_high: 250
    price_threshold_low: 150
    volume_spike_percent: 50
  AMZN:
    price_threshold_high: 250
    price_threshold_low: 100
    volume_spike_percent: 50
  GOOGL:
    price_threshold_high: 200
    price_threshold_low: 100
    volume_spike_percent: 50
  MSFT:
    price_threshold_high: 500
    price_threshold_low: 300
    volume_spike_percent: 50
portfolio:
  tickers:
  - AAPL
  - GOOGL
  - MSFT
  - AMZN
slack:
  dry_run: true
  webhook_url: ''
